---
inventory:
       plugin: SimpleInventory
       options:
            host_file: 'inventory/hosts.yaml'
            group_file: 'inventory/groups.yaml'
            defaults_file: 'inventory/creds.yaml'
runner:
       plugin: threaded
       options:
            num_workers: 10